os: osx
language: generic
osx_image: xcode9.3
env:
   global:
     - CONAN_REFERENCE: "darwin-toolchain/1.0.0"
     - CONAN_USERNAME: "ezored"
     - CONAN_LOGIN_USERNAME: "prsolucoes"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/ezored/conan-darwin-toolchain"
     - CONAN_STABLE_BRANCH_PATTERN: "stable/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
