os: osx
language: generic
osx_image: xcode11.2
env:
  global:
    - CONAN_REFERENCE: "darwin-toolchain/1.3.0"
    - CONAN_USERNAME: "ezoredrepository"
    - CONAN_CHANNEL: "stable"
    - CONAN_UPLOAD: "https://ezoredrepository.jfrog.io/artifactory/api/conan/conan-local"
    - CONAN_STABLE_BRANCH_PATTERN: "stable/*"
    - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
